//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halcones.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class AERONAVE
    {
        public AERONAVE()
        {
            this.COMPONENTES_AERONAVE = new HashSet<COMPONENTES_AERONAVE>();
            this.MANTENIMIENTO_AERONAVE = new HashSet<MANTENIMIENTO_AERONAVE>();
            this.VUELO = new HashSet<VUELO>();
        }
    
        public decimal ID_AERONAVE { get; set; }
        public string MATRICULA { get; set; }
        public decimal TOTAL_SEGUNDOS_VUELO { get; set; }
        public System.DateTime FECHA_INSPECCION_ANUAL { get; set; }
        public System.DateTime FECHA_AERONAVEGABILIDAD { get; set; }
        public Nullable<decimal> ANNO_FABRICACION { get; set; }
        public Nullable<decimal> DIAS_MANTENCION { get; set; }
        public Nullable<decimal> HORAS_VUELO_MANTENCION { get; set; }
        public Nullable<decimal> TOTAL_HORAS_VUELO_MANTENCION { get; set; }
        public Nullable<System.DateTime> ULTIMO_MANTENIMIENTO { get; set; }
        public string ESTADO { get; set; }
        public decimal ID_TIPO_AERONAVE { get; set; }
    
        public virtual ICollection<COMPONENTES_AERONAVE> COMPONENTES_AERONAVE { get; set; }
        public virtual ICollection<MANTENIMIENTO_AERONAVE> MANTENIMIENTO_AERONAVE { get; set; }
        public virtual TIPO_AERONAVE TIPO_AERONAVE { get; set; }
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
