//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halcones.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPONENTES_AERONAVE
    {
        public decimal ID_COMPONENTE_AERONAVE { get; set; }
        public decimal TOTAL_SEGUNDOS_VUELO { get; set; }
        public decimal ID_AERONAVE { get; set; }
        public decimal ID_COMPONENTE { get; set; }
    
        public virtual AERONAVE AERONAVE { get; set; }
        public virtual COMPONENTE COMPONENTE { get; set; }
    }
}
