//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halcones.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPONENTE
    {
        public COMPONENTE()
        {
            this.COMPONENTES_AERONAVE = new HashSet<COMPONENTES_AERONAVE>();
            this.COMPONENTES_COMPONENTE = new HashSet<COMPONENTES_COMPONENTE>();
            this.COMPONENTES_COMPONENTE1 = new HashSet<COMPONENTES_COMPONENTE>();
            this.MATENIMIENTO_COMPONENTE = new HashSet<MATENIMIENTO_COMPONENTE>();
        }
    
        public decimal ID_COMPONENTE { get; set; }
        public string COMPONENTE1 { get; set; }
        public string FABRICANTE { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<COMPONENTES_AERONAVE> COMPONENTES_AERONAVE { get; set; }
        public virtual ICollection<COMPONENTES_COMPONENTE> COMPONENTES_COMPONENTE { get; set; }
        public virtual ICollection<COMPONENTES_COMPONENTE> COMPONENTES_COMPONENTE1 { get; set; }
        public virtual ICollection<MATENIMIENTO_COMPONENTE> MATENIMIENTO_COMPONENTE { get; set; }
    }
}
