//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halcones.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDICION_VUELO
    {
        public CONDICION_VUELO()
        {
            this.VUELO = new HashSet<VUELO>();
        }
    
        public decimal ID_CONDICION { get; set; }
        public string CONDICION { get; set; }
    
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
