//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halcones.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HalconesEntities : DbContext
    {
        public HalconesEntities()
            : base("name=HalconesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AERONAVE> AERONAVE { get; set; }
        public DbSet<COMPONENTE> COMPONENTE { get; set; }
        public DbSet<COMPONENTES_AERONAVE> COMPONENTES_AERONAVE { get; set; }
        public DbSet<COMPONENTES_COMPONENTE> COMPONENTES_COMPONENTE { get; set; }
        public DbSet<CONDICION_VUELO> CONDICION_VUELO { get; set; }
        public DbSet<LICENCIA> LICENCIA { get; set; }
        public DbSet<LICENCIA_PILOTO> LICENCIA_PILOTO { get; set; }
        public DbSet<LLEGADA_VUELO> LLEGADA_VUELO { get; set; }
        public DbSet<MANTENIMIENTO_AERONAVE> MANTENIMIENTO_AERONAVE { get; set; }
        public DbSet<MATENIMIENTO_COMPONENTE> MATENIMIENTO_COMPONENTE { get; set; }
        public DbSet<MISION> MISION { get; set; }
        public DbSet<PERFIL> PERFIL { get; set; }
        public DbSet<PILOTO> PILOTO { get; set; }
        public DbSet<TIPO_AERONAVE> TIPO_AERONAVE { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VUELO> VUELO { get; set; }
    
        public virtual int PRO_ESTADO_LICENCIA_PILOTO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_ESTADO_LICENCIA_PILOTO");
        }
    
        public virtual int PRO_ESTADO_VUELO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_ESTADO_VUELO");
        }
    
        public virtual int PRO_PRUEBA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_PRUEBA");
        }
    }
}
