//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halcones.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PILOTO
    {
        public PILOTO()
        {
            this.LICENCIA_PILOTO = new HashSet<LICENCIA_PILOTO>();
            this.VUELO = new HashSet<VUELO>();
            this.VUELO1 = new HashSet<VUELO>();
        }
    
        public decimal ID_PILOTO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string COMUNA { get; set; }
        public string DIRECCION { get; set; }
        public System.DateTime MEDICINA_AEROSPACIAL { get; set; }
        public decimal TOTAL_SEGUNDOS_VUELO { get; set; }
        public decimal ID_USUARIO { get; set; }
    
        public virtual ICollection<LICENCIA_PILOTO> LICENCIA_PILOTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<VUELO> VUELO { get; set; }
        public virtual ICollection<VUELO> VUELO1 { get; set; }
    }
}
