//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halcones.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_AERONAVE
    {
        public TIPO_AERONAVE()
        {
            this.AERONAVE = new HashSet<AERONAVE>();
        }
    
        public decimal ID_TIPO_AERONAVE { get; set; }
        public string TIPO_AERONAVE1 { get; set; }
    
        public virtual ICollection<AERONAVE> AERONAVE { get; set; }
    }
}
