//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halcones.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.PILOTO = new HashSet<PILOTO>();
        }
    
        public decimal ID_USUARIO { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string CORREO { get; set; }
        public string RUT { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string ESTADO { get; set; }
        public decimal ID_PERFIL { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
        public virtual ICollection<PILOTO> PILOTO { get; set; }
    }
}
