//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halcones.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUELO
    {
        public VUELO()
        {
            this.LLEGADA_VUELO = new HashSet<LLEGADA_VUELO>();
        }
    
        public decimal ID_VUELO { get; set; }
        public System.DateTime FECHA_SALIDA { get; set; }
        public string ESTADO { get; set; }
        public string ORIGEN { get; set; }
        public string DESTINO { get; set; }
        public decimal ID_AERONAVE { get; set; }
        public decimal ID_PILOTO { get; set; }
        public decimal ID_COPILOTO { get; set; }
        public decimal ID_CONDICION { get; set; }
        public decimal ID_MISION { get; set; }
    
        public virtual AERONAVE AERONAVE { get; set; }
        public virtual CONDICION_VUELO CONDICION_VUELO { get; set; }
        public virtual ICollection<LLEGADA_VUELO> LLEGADA_VUELO { get; set; }
        public virtual MISION MISION { get; set; }
        public virtual PILOTO PILOTO { get; set; }
        public virtual PILOTO PILOTO1 { get; set; }
    }
}
